// shows all bands for bands.html
fetch("thedatabase.json") // This file is auto-generated by CMS
    .then(response => response.json())
    .then(person => {
        let container = document.getElementById("bandsdiv");
        person.forEach(persons => {
            let div = document.createElement("div");
            // const imageSrc = persons.image && persons.image.startsWith("http")
            //     ? persons.image
            //     : persons.image
            //         ? `${persons.image}`
            //         : "placeholder.png";

            div.setAttribute('id', 'band');
            div.innerHTML = `
                <-- <img src="${persons.image}"> -->
                <a>${persons.name}</a>
                <p>${persons.status}</p>
            `;
            container.appendChild(div);
        });

    });
